In [1]:
import torch

In [2]:
import torch.nn as nn

In [13]:
from  torch.nn import functional as F

In [4]:
x = nn.Embedding(5,5)

In [21]:
F.cross_entropy(torch.randn(5,15),torch.tensor([1,1,1,1,1]))

tensor(2.4617)

In [29]:
torch.zeros(1,1,dtype=torch.long)

tensor([[0]])

In [ ]:
type(x)

torch.nn.modules.sparse.Embedding

In [ ]:
x.weight

Parameter containing:
tensor([[ 0.5920,  0.7454,  1.5669, -0.9547,  0.3468],
        [-0.0776, -1.0254,  0.2983, -2.3331,  0.5777],
        [-0.5072, -0.2032,  0.8440,  0.4730, -1.1815],
        [-0.7468, -0.2608, -0.2179,  0.8875, -0.0825],
        [ 0.2731, -0.4676, -1.6599,  0.3158,  0.5065]], requires_grad=True)

In [9]:
torch.randn(5,5,requires_grad=True)

tensor([[ 0.7283,  0.8597,  0.1315,  2.1375, -0.5208],
        [-1.9750,  2.2122, -0.7271, -0.2539,  0.3775],
        [ 1.5154,  0.8377,  0.1744, -0.6713, -0.2396],
        [ 1.0413, -0.4295,  0.7405, -0.6846,  1.7102],
        [-0.0325,  0.1737, -1.4067, -0.7784,  0.3489]], requires_grad=True)