In [13]:
# Environment check: confirm we are on the venv interpreter (not python3.13t)
import sys
print("python:", sys.executable)

python: c:\Users\Ravi.Seemala\Downloads\project\nn-learning\.venv\Scripts\python.exe


In [14]:
import torch
import numpy as np
import matplotlib.pyplot as plt


In [15]:
names = open('names.txt','r').read().splitlines()
names = ['.'+i+'.' for i in names]
biagrams = []
for i in names:
    for j in range(len(i)-1):
        biagrams.append(i[j]+i[j+1])

stoi = []
for i in names:
    for j in i:
        if j not in stoi:
            stoi.append(j)
rstoi = {}
for num,i in enumerate(sorted(set(stoi))):
    rstoi[i] = num

inp,out = [],[]
for i in biagrams:
    inp.append(rstoi[i[0]])
    out.append(rstoi[i[1]])

In [108]:
torch.zeros(3,4)[1].reshape(1,-1)

tensor([[0., 0., 0., 0.]])

In [102]:
torch.zeros(1,4)

tensor([[0., 0., 0., 0.]])

In [95]:
onehot[1].shape

torch.Size([27])

In [118]:
t = torch.rand(1,5)

In [122]:
(t+15)/5

tensor([[3.0210, 3.0200, 3.0476, 3.1873, 3.0990]])

In [113]:
onehot[1].to(torch.float32).dtype

torch.float32

In [135]:
import torch.nn.functional as F 
onehot = []
for i in inp:
    t = F.one_hot(torch.tensor(i),num_classes=27).to(torch.float32)
    onehot.append(t)

weights = torch.randn(27,27,requires_grad=True)

loss = torch.tensor(0.0)
for index,i_onhot in enumerate(onehot):
    mlp_out = i_onhot.reshape(1,-1)@weights
    mlp_out = mlp_out.squeeze(0)
    exp = torch.exp(mlp_out)
    sum = torch.sum(exp)
    average = exp/sum
    pick = torch.log(average[out[index]]) * -1
    loss += pick
loss = loss/len(onehot)


In [136]:
loss

tensor(3.6873, grad_fn=<DivBackward0>)